name: Deploy to Firebase Hosting on PR
on: 
  pull_request:
    branches:
      - main

jobs:

  test_and_build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node-JS Version
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build Project
        run: npm run build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build

  build_and_preview:
    runs-on: ubuntu-latest
    needs: test_and_build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SKOOLINVIVO18 }}'
          projectId: skoolinvivo18
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
